sudo: required
language: cpp
compiler: clang
branches:
  only:
  - master
  - "/^v\\d+\\./"
os:
- linux

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_script:
- cd renderer && mkdir build && cd build
- pwd
- cmake --version

script:
- cmake ..
- make
find . -name \*.a -print
- make test

notifications:
- email: false
